services:
  container1:
  mysql:
    image: mysql
    container_name: mysql_project_container
    environment:
      - MYSQL_ROOT_PASSWORD = mysql
      - MYSQL_TCP_PORT = 15000
    network_mode: host
    volumes:
      - ~mysql:/var/lib/mysql
